### ISSUE TITLE
Local config

### ISSUE THREAD

**Issue by kkobashi** [turnermm/tocselect#1]
Need to remove the local.php config statement when user uninstalls the plugin:
`$conf['plugin']['tocselect']['notoc'] = '1';`

This shows up in the configuration settings undefined section. This is harmless, however I'd rather not see it.

**Comment by turnermm** [comment]
This is a dokuwiki issue.   Dokuwiki leaves config options behind after a plugin or template is uninstalled.  You can remove it manually by deleting it from loclal.php yourself.
